############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
  name  = "Services"
  weight = 3
  identifier = "services"

  [[main]]
    parent = "services"
    name   = "Pressure Washing"
    url    = "/english/service/pressure-washing/pressure-washing/"
    weight = 1

  [[main]]
    parent = "services"
    name   = "Fire & Safety"
    url    = "/english/service/fire-safety/fire-safety/"
    weight = 2
    
  [[main]]
    parent = "services"
    name   = "Technology Solutions & Structured Cabling"
    url    = "/english/service/technology/technology/"
    weight = 3

[[main]]
  name  = "Industries"
  weight = 4
  identifier = "industries"

  [[main]]
    parent = "industries"
    name   = "Medical"
    url    = "industry/medical/"
    weight = 1

  [[main]]
    parent = "industries"
    name   = "Dental"
    url    = "industry/dental/"
    weight = 2

  [[main]]
    parent = "industries"
    name   = "Vision Care"
    url    = "industry/vision/"
    weight = 3

  [[main]]
    parent = "industries"
    name   = "Radiology"
    url    = "industry/radiology/"
    weight = 4

  [[main]]
    parent = "industries"
    name   = "Education"
    url    = "industry/education/"
    weight = 5

  [[main]]
    parent = "industries"
    name   = "Government"
    url    = "industry/government/"
    weight = 6

  [[main]]
    parent = "industries"
    name   = "Non-Profit"
    url    = "industry/non-profit/"
    weight = 7

  [[main]]
    parent = "industries"
    name   = "SMB"
    url    = "industry/smb/"
    weight = 8

  [[main]]
    parent = "industries"
    name   = "Corporate & Enterprise"
    url    = "industry/corporate/"
    weight = 9

  [[main]]
    parent = "industries"
    name   = "Hospitality"
    url    = "industry/hospitality/"
    weight = 10
  
  [[main]]
    parent = "industries"
    name   = "Restaurants"
    url    = "industry/restaurant/"
    weight = 11


#[[main]]
#name = "Blog"
#url = "blog/"
#weight = 4

#[[main]]
#name = "Team"
#url = "team/"
#weight = 5

[[main]]
name = "Contact"
url = "contact/"
weight = 5

#[[main]]
#hasChildren = true
#name = "Pages"
#weight = 8

#[[main]]
#name = "Project"
#parent = "Pages"
#url = "project/"

#[[main]]
#name = "Pricing"
#parent = "Pages"
#url = "pricing/"

#[[main]]
#name = "Elements"
#parent = "Pages"
#url = "elements/"

# footer menu
#[[footer]]
#name = "Legal"
#url = "#"
#weight = 1

#[[footer]]
#name = "Sitemap"
#url = "#"
#weight = 

[[footer]]
name = "Privacy Policy"
url = "#"
weight = 3

[[footer]]
name = "Terms & Conditions"
url = "#"
weight = 4
