steps:
  build:
    image: hugomods/hugo:latest
    commands:
      - hugo --minify

  docker-build:
    image: docker:dind
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build -t 192.168.30.11:5000/hugo-site:latest .
      - docker push 192.168.30.11:5000/hugo-site:latest